Morpho-lang/morpho

- morpho5/datastructures/value.h
- test/operator/more_comparison.morpho
In the function `morpho_ofsametype`, if the operand `a` is not a float, then the type tag bits for both `a` and `b` are checked. However, if `b` is a float, then we have a problem as valid floating point values will have the type bits set, leading to an incorrect result that both types are the same even when they are not. This can be resolved by checking if either operand is a float first, and only moving to the second branch if neither operand is a float.
This should resolve #41.
> Check both operands for float type before checking type tag

- morpho5/docs/povray.md
- morpho5/modules/povray.morpho
When rendering `POVRaytracer` objects in a loop, one might want to turn graphic display off. I added an optional `display=true` flag to the `render` method that achieves this, while not affecting the default behavior. When `display=false`, an optional flag of `-D` is added to the `povray` system call, which turns off the graphic display.
I am not sure how to add an automated test for this, but here is a MWE that generates `test.pov` and `test.png` without opening up the graphic display:
`import meshtools`
`import plot`
`import povray`
`var m = LineMesh(fn (t) [t,0,0], -1..1:0.2)`
`var g = plotmesh(m)`
`var pov = POVRaytracer(g)`
`pov.render("test.pov", display=false)`
Removing the `display` flag or setting it to `true` should result in the default behavior. Tested on Ubuntu 20.04 and on …
> Added optional flag to turn off display in POVRaytracer render 

- morpho5/geometry/selection.c
- test/selection/boundary.morpho
My attempt at making sure that the boundary selection has grade 0 elements. I noticed that Selections made using anonymous functions do have grade 0 elements, but the ones made using `boundary=true` only have grade `(mesh.maxgrade()-1)` elements. I added a simple line to `selection_selectboundary` to add grade 0 elements if it's not a 1D mesh. I have also updated the boundary.morpho test which now returns the correct `idlistforgrade(0)` of the selection even without adding grade 0 explicitly.
Not sure whether this is the ideal way of solving the problem though.
> Boundary selection now has guaranteed grade 0 elements. Updated test.

- morpho5/build.h
- morpho5/interface/cli.c
This adds an optional extended welcome message in the CLI with an ASCII blue butterfly and links to the code and documentation. 
To turn it on, uncomment line 161 in build.h, which will define a `MORPHO_LONG_BANNER` flag.
> Added optional ASCII butterfly in the CLI-welcome

- morpho5/geometry/mesh.c
- test/mesh/addgradezero.morpho
Adding grade 0 elements to a mesh should do nothing since all meshes are required to have them. However, upon calling `addgrade(0)` on a mesh, the connectivity matrix for (0,0) was being set equal to the connectivity matrix of (0,1), causing unwanted problems. (This was probably happening at line 327 in the function `mesh_addgrade`.)
With this fix, the `Mesh_addgrade` function returns `MORPHO_NIL` if grade is 0. Additionally, the `mesh_setconnectivityelement` function now returns `false` if `row` and `col` are same, making sure that the diagonal connectivity matrices are untouched. (Assuming those are always supposed to be `nil`.)
A new test `test/mesh/addgradezero.morpho` ensures that the connectivitymatrix(0,0) remains `nil` upon adding grade 0.
This should resolve #50.
Co-Authored-By: …
> Adding grade 0 to a mesh should now do nothing. Added test.

- examples/povray/testpovraytransmitfilter.morpho
- morpho5/docs/graphics.md
- morpho5/modules/graphics.morpho
- morpho5/modules/plot.morpho
- morpho5/modules/povray.morpho
The POV-Ray library provides a couple parameters to make objects transparent, namely `transmit` and `filter` (see [here](http://xahlee.info/3d/povray-glassy.html) for the POV-Ray documentation). This PR would allow users to pass these as arguments to `Graphics` objects like `Sphere`, `Cylinder`, etc. and the effect would show up in the corresponding `POVRaytracer` output. For example,
`var g = Graphics()`
`g.display(Sphere(Matrix([0,0,0]), 1, transmit=0.75))`
These arguments can also be passed to `plotmesh`, `plotselection` and `plotfield`. The effect is currently not visible in the `morphoview` application. 
As an example / test of this, another file is added under `examples/povray` that generates objects with varying values of the `transmit` and `filter` parameters. Here is the output …
> Added `transmit` and `filter` options for Graphics objects, to be used by POV-Ray 

- morpho5/builtin/functions.c
- morpho5/builtin/veneer.c
- morpho5/interface/cli.c
- morpho5/utils/common.h
- morpho5/vm/vm.c
Fixes #72. morpho_comparevalue has been documented with a warning about using to order values. MORPHO_CHECKCMPTYPE now provided. 
min, max and List.sort all fixed that demonstrated erroneous behavior
I added a test.
> Minorfixes

- morpho5/builtin/functions.c
- morpho5/builtin/functions.h
- morpho5/datastructures/value.c
- morpho5/datastructures/value.h
- morpho5/docs/builtin.md
- morpho5/docs/functions.md
- morpho5/geometry/functional.c
- morpho5/utils/common.c
- morpho5/utils/debug.c
- morpho5/utils/parse.c
- morpho5/vm/compile.c
- morpho5/vm/core.h
- morpho5/vm/vm.c
- test/apply/apply_list.morpho
- test/builtin/bounds.morpho
- test/builtin/boundsvargs.morpho
- test/builtin/maxargs.morpho
- test/builtin/minargs.morpho
- test/builtin/minvargs.morpho
- test/builtin/typecheck.morpho
- test/closure/closures_in_loop.morpho
- test/function/anonymous_closure_noparams.morpho
- test/functionals/scalarpotential/scalarpotential_ndiff.morpho
- test/try/try_reentrancy_uncaught.morpho
- test/type/typecheck.morpho
A number of small improvements and fixes that aid the meshgen module. 
- min, max and bounds can accept multiple arguments; none of which have to be lists. So things like:
min(1,2,-1)
are supported.
- ScalarPotential will calculate numerical gradients if a gradient function isn't provided. 
- Apply now will apply the function specified to a List IF that is the only other argument, e.g. 
apply(f, [1,2,3]) // f(1,2,3) 
- Additions to help to support the above. 
- Stacktraces now display correctly again.
- Anonymous functions now return upvalues and globals correctly. Fixed #83.
> Language improvements to support meshgen

- manual/src/Reference/array.tex
- manual/src/Reference/list.tex
- morpho5/builtin/veneer.c
- morpho5/builtin/veneer.h
- morpho5/datastructures/matrix.c
- morpho5/datastructures/matrix.h
- morpho5/docs/array.md
- morpho5/docs/list.md
- morpho5/utils/parse.c
- morpho5/vm/vm.c
- test/matrix/nonnum_indices.morpho
- test/slice/arraySlicing.morpho
- test/slice/listSlicing.morpho
- test/slice/matrixSlicing.morpho
This submission adds slicing as a option for indexing 
for Lists, Arrays and Matrices you can use ranges and lists to specify which elements you want.
Next task it to add ... as an open range.
Are there any other objects that would benefit from slice indexing? sparse matrices? 
This code has been placed in veneer.c near the array handling do  you have better suggestions for its placement?
I also create an arrayerror -> matrixerror function to throw the correct kind of error depending on what the object being indexed is.
> Allow slice indexing of arrays and lists

- morpho5/vm/compile.c
- test/property/index_property_in_args.morpho
compile_list did not correctly retain registers as it was constructing the list, leading to garbage values. This is now fixed and a test added to lock down this behavior.
Fixes #112
> Fix register allocation issue in list creation

- morpho5/builtin/veneer.c
- test/range/exclusive.morpho
- test/range/inclusive.morpho
- test/range/syntax.morpho
In the `range_count` function, floating point error would lead to inaccurate calculation of the size of an inclusive range. 
In the case of the example shown in #105, with `start = 0.1`, `end = 2.0`, and `step = 0.1`, we compute the number of elements in the range to be `1 + (int) ((2.0 - 0.1) / 0.1) = 1 + (int) (18.99...96) = 19` which is off by one. Instead, we need to make sure to take the ceiling of the result before casting to an integer.
I additionally removed a possible integer division by 0, as well as added checks for infinities and nans before casting to an integer. In these cases, I take the number of elements to be 0 since there's no well-defined set of elements to return.
This should resolve #105
> More careful calculation of inclusive range limits (fixes #105)

- benchmark/benchmark.py
- morpho5/utils/debug.c
- morpho5/vm/compile.c
- morpho5/vm/core.h
- morpho5/vm/opcodes.h
- morpho5/vm/vm.c
Alternative instruction set: Remove constants as possible arguments, and hence increase the number of opcodes to 256. No obvious change in performance.
> Altinstruction

- morpho5/modules/vtk.morpho
- test/vtk/export_and_import_vector_2d.morpho
This PR fixes a small bug in the VTK module. VTK Vectors are always 3D, so we need to append a 0 for the z component when the field is 2D.
Added a test to lock down the behavior.
> Fixed export of 2D fields

- morpho5/geometry/field.c
- morpho5/geometry/field.h
- morpho5/geometry/functional.c
- morpho5/geometry/functional.h
- test/functionals/hydrogel/hydrogel_field_lacks_grade.morpho
Using Hydrogel with a Field was very error prone; the Field needs to have scalars on the same grade as the element. 
Added an error to alert the user if the Field didn't have the right information, and a test case to ensure the error is generated correctly.  
Fixes #124.
> Hydrogel Errors

- morpho5/modules/povray.morpho
Fix the following type of error
To reproduce the error:
// ** deltaSigma = -0.25
// ** angle[0] = [82.6, 88.8, 85.94, 105.72]
// ** angle[1] = 71
var surface = PolyhedronMesh([[-2.5,2.5,-0.5],[2.5,2.5,-0.5],[-2.5,-2.5,-0.5],[2.5,-2.5,-0.5],
[-2.5,2.5,-1],[2.5,2.5,-1],[-2.5,-2.5,-1],[2.5,-2.5,-1]],
[[0,1,3,2], [0,1,5,4], [0,2,6,4], [7,3,2,6],
[1,3,7,5], [4,6,7,5]])
var graphic2 = plotmesh(surface, grade=[0,1,2])
var pov = POVRaytracer(graphic2)
pov.viewpoint=Matrix([0, -4, -5])
pov.viewangle=0
pov.light=[Matrix([10,10,10]), Matrix([-10,-10,10])]
pov.render("${deltaSigma}_${angle[1]}.pov", display=true, quiet=false)
/*  1.throwing error in the render() method in the POVRaytracer class at morpho/morpho5/modules/povray.morpho
line 164 executed command in shell "povray -0.25_90.pov +A +W2048 …
> Fixed Latent Error for render() method

- morphoview/command.c
The warning appearing during morphoview installation is due to not checking the return value of a `system` call. The `system` call in this case (command.c:34.5) is meant to delete a temporary command file, which I believe is not critical to the functioning of Morpho? I have for now modified the file so that it prints a warning if the `system` call fails. Should we produce an error instead?
This fixes #137
> Viewwarning

- morpho5/build.h
- morpho5/utils/error.h
- morpho5/vm/core.h
- morpho5/vm/vm.c
- test/function/stack_overflow.morpho
VM now checks for stack overflow and reports an error when it occurs. Callframe stack increased to 255 levels]
> Function calls can now raise a stack overflow

- morpho5/docs/color.md
- morpho5/modules/color.morpho
Improvements to the color module:
A number of additional named colors: Cyan, Orange, Magenta, etc.
Four new ColorMaps MagmaMap, ViridisMap, InfernoMap, PlasmaMap that are derived from efforts to make color vision deficiency friendly schemes [https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html#the-color-scales]
The new color maps are based on chebyshev expansion, and additional maps can easily be added as subclasses of ChebyshevMap.
Documentation updated to reflect the above and improve the coverage of the help.
> Improvements to color module

- morpho5/modules/meshtools.morpho
- test/modules/meshtools/merge_duplicates.morpho
- test/modules/meshtools/testrefine3d.morpho
mesh tools now provides a data structure, ElementList, that helps efficiently identify duplicate elements. The particular implementation could be improved upon, especially for elements of grade 3 or higher, but works now.
* MeshMerge has been updated to check for duplicates. This fixes #149 
* MeshRefiner has been updated to check for duplicates, fixing unreported bugs. 
Tests have been added.
> Meshtools duplicate checking 

- morpho5/Makefile.linux
- morpho5/build.h
- morpho5/builtin/builtin.c
- morpho5/builtin/builtin.h
- morpho5/datastructures/object.c
- morpho5/datastructures/object.h
- morpho5/interface/cli.c
- morpho5/interface/cli.h
- morpho5/main.c
- morpho5/modules/graphics.morpho
- morpho5/morpho.h
- morpho5/vm/compile.c
- morpho5/vm/core.h
- morpho5/vm/vm.c
Implements a simple profiler: A second thread watches the VM as it continues and logs the current function from the call frame. There's little to no overhead for this. The output is a histogram of samples indicating where the program is spending its time. 
To use, run morpho with the -profile flag. The profile info is output after execution is finished.
> Simple Profiler

- morpho5/geometry/functional.c
The Hydrogel functional's gradient was being computed numerically, which was the most expensive process in the minimization by far (~95% of the time spent). This PR implements the analytical computation of the gradient, giving the minimization a ~7.5x speed up.
> Hydrogel speedup

- morpho5/builtin/veneer.c
- morpho5/builtin/veneer.h
- morpho5/datastructures/dictionary.c
- morpho5/docs/dictionary.md
- test/dictionary/clear.morpho
- test/dictionary/remove.morpho
- test/dictionary/tombstone.morpho
* `clear` and `remove` methods added to the Morpho Dictionary object
* Updated docs and added new corresponding tests
* Small comment fixes
* Possible fix for a tombstone-related bug
The `clear` method is useful when you need a new blank dictionary inside a loop, avoiding the creation of a new Dictionary object every time. The combination of `remove` and `clear` could be very useful (if the bug is fixed) in accelerating the delaunay / meshgen modules.
I have also attempted to fix a rather tricky bug which was resulting in the silent failing of dictionary insertion when enough remove and add operations have been performed. I am not sure whether my fix is the right one. I have added a test for it, and all the other tests are passing.
What's happening in the current implementation is that …
> Dictionary improvements and fix

- morpho5/geometry/functional.c
- test/functionals/hydrogel/hydrogel1D.morpho
- test/functionals/hydrogel/hydrogel1D_2elements.morpho
- test/functionals/hydrogel/hydrogel2D.morpho
- test/functionals/hydrogel/hydrogel2D_2elements.morpho
- test/functionals/hydrogel/hydrogel3D_2elements.morpho
* New `functional_elementgradient` helper method added. Gradient methods can now be made dimensionally independent easily. 
* The new hydrogel_gradient method is now fixed to work in any dimension
* Added tests for hydrogel in 1D and 2D.
This fixes #174
> New hydrogel_gradient that works in any dimension

- morpho5/docs/meshgen.md
- morpho5/modules/delaunay.morpho
- morpho5/modules/meshgen.morpho
* Delaunay triangulation that uses a Dictionary of exterior simplices instead of a List, thus eliminating the need for deduplication and accelerating the triangulation quite a bit.
* Includes few other small improvements like initializing variables outside a for loop /  making them attributes of the Delaunay object, etc.
* MeshGen's `MGShapeOptimizer` now uses a stepsize and steplimit that doesn't allow initial movement of vertices beyond the tolerance `ttol`. This fixes the failure of the current MeshGen for high resolution meshes.
* Small update to meshgen docs to include `maxiterations`
> Delaunay + MeshGen improvements

- morpho5/utils/error.h
- morpho5/vm/compile.c
- morpho5/vm/vm.c
- test/try/err_stack_overflw.morpho
- test/try/return_in_try.morpho
* PUSHERR now checks for err stack overflow. 
* RETURN now removes error handlers from the current call frame. 
The above now fixes a bug whereby using return in a try statement could generate a segfault.
> Return in try

- morpho5/builtin/veneer.c
- morpho5/builtin/veneer.h
- test/object/has.morpho
- test/object/responds_to.morpho
adds .has() and .respondsto() for no arguments, returning a list of all properties for .has() and a list all methods for .respondsto()
I couldn't find where has  .has and .respondsto were previously document to add the new functionality
This change does not fix #182
> Respondsto

- morpho5/interface/linedit.c
- morpho5/interface/linedit.h
Insertion of UTF8 characters would previously cause problems in interactive mode. This PR partially fixes the problem: linedit is now utf8 aware and correctly parses wide characters. There are still further improvements—the display width of the character is not established here, for example, but this is still a worthwhile improvement.
> Improvements to utf8 support in interactive mode

- morpho5/utils/parse.c
- morpho5/vm/compile.c
- test/function/anonymous_in_args.morpho
- test/function/anonymous_in_optional_args.morpho
Improvements to parser and compiler: You can now specify anonymous functions in the arguments to a function.
> Anonymous functions work in args

- morpho5/build.h
- morpho5/builtin/builtin.c
- morpho5/geometry/field.c
- morpho5/geometry/field.h
- morpho5/geometry/functional.c
- morpho5/geometry/functional.h
- morpho5/main.c
- morpho5/morpho.h
- morpho5/utils/common.c
- morpho5/utils/common.h
- morpho5/vm/core.h
- morpho5/vm/vm.c
- test/functionals/area/area2.morpho
- test/functionals/lineintegral/lineintegral_fieldgradient.morpho
- test/functionals/lineintegral/selection.morpho
- test/functionals/nematicelectric/nematicelectric.morpho
This PR uses a thread pool to parallelize force and energy calculations, giving a considerable speedup for programs where these are the limiting factor.
To use, simply run morpho with -wX where X is the number of worker threads to use.
Note that there is an outstanding (and tricky) issue to resolve with clock(): it reports the CPU time not the wall time. For now, use an external timing utility. There seems to be a lack of platform independent solutions to report wall time at the right level of granularity.
> Multithreaded force and energy calculations

- morpho5/Makefile.linux
- morpho5/build.h
- morpho5/builtin/system.c
- morpho5/builtin/system.h
- morpho5/docs/system.md
- morpho5/main.c
- morpho5/morpho.h
- morpho5/utils/memory.c
- morpho5/utils/memory.h
- test/system/args.morpho
- test/system/args.xmorpho
This PR includes a number of new methods on the System class, designed to help morpho scripts interact with the environment: 
- clock() now returns wall time rather than process time, which helps with benchmarking.
- sleep() now pauses morpho for a specified amount of time.
- readline() reads a single line of text from stdin. 
- arguments() returns command line arguments passed to morpho *after* the filename.
> New System functionality

- morpho5/Makefile
- morpho5/Makefile.linux
- morpho5/Makefile.m1
- morpho5/utils/common.c
This PR fixes a number of bugs in the resource finder. 
* File extensions are now handled correctly.
* Resource finder now checks that a morpho extension links AND initializes correctly before returning success. 
* File names now match exactly rather than partially. 
Additionally the make files have been updated to ensure a library folder always exists for morpho extensions.
> Fixresource

- modules/meshtools.morpho
- src/geometry/functional.c
This PR fixes a minor bug in MeshPruner that could occasionally generate duplicate elements. The new algorithm explicitly checks for duplicates.
A check in area_functional and length_functional prevents a possible SEGFAULT if a badly formed element is incorrectly passed to these functions.
> Fix duplicate element generation

- help/complex.md
Randomly noticed this misspelling of subtopics causing this in the RTD. 
This PR fixes that.
> Fix typo in complex.md

- help/complex.md
The complex.md contains a `subtopics` command without parenthesis, causing incorrect behavior in the RTD. This fixes that.
> Fix parenthesis

- .github/workflows/buildandtestmultithreaded.yml
- .gitignore
- README.md
- test/test.py
This PR attempts to add a CI workflow to run the test-suite with `morpho6 -w2`, thus checking for bugs with multithreading.
Given the increase in parallelization in Morpho (yay!), this could be quite useful to spot bugs like #259 
It essentially adds one more argument flag to test.py and invokes it in the new workflow.
> CI workflow to perform automated testing with multithreading

- examples/examples.py
- modules/graphics.morpho
- modules/povray.morpho
This small PR uses the new multiple dispatch functionality to simplify the visitor pattern used in the graphics module, where the graphics primitives are visited by `Show` and `POVRaytracer`. 
All examples tests are passing. 
It also updates the run command in the `examples.py` file, providing a temporary band-aid for #263 .
> Visitor pattern for Graphics simplified with Multiple Dispatch

- test/types/multiple_dispatch/duplicate_no_type.morpho
- test/types/multiple_dispatch/duplicate_no_type_two_arguments.morpho
- test/types/multiple_dispatch/duplicate_one_arg.morpho
- test/types/multiple_dispatch/namespace_for_new.morpho
- test/types/multiple_dispatch/namespace_for_overwrite.morpho
A few more tests for multiple dispatch. The `namespace_for_new` test implements a new signature for a function in the namespace, and Morpho does run that implementation. Not sure what the intended behavior is here. I feel like this should be allowed as it will allow users to re-use code nicely.
Not sure about the `namespace_for_overwrite`, which tries to redefine an already existing implementation from the namespace. I think this should just result in a standard multiple dispatch error of matching signatures. 
`duplicate_no_types_two_arguments` is same as the `duplicate` test, but the signature doesn’t contain types. This works correctly. The `duplicate_no_types` however has duplicate functions with a _single_ untyped argument, and this fails due to a segfault. So does the …
> More tests for multiple dispatch

- src/classes/function.h
- src/classes/metafunction.c
- src/classes/metafunction.h
- src/core/compile.c
- src/core/compile.h
- src/core/vm.c
- src/datastructures/error.h
- src/geometry/functional.c
- test/types/multiple_dispatch/class_multiple_dispatch_post.morpho
- test/types/multiple_dispatch/class_multiple_initializer.morpho
- test/types/multiple_dispatch/duplicate_no_type_two.morpho
Improves multiple dispatch on classes. Methods are not inherited correctly, and overwrite older methods with equivalent signatures. 
Multiple initializer methods can now be provided in class definitions, and they are selected correctly by the virtual machine.
> Class multiple dispatch

- help/errors.md
- src/classes/err.c
- src/core/vm.c
- src/datastructures/error.h
- test/error/throw_on_class.morpho
- test/error/throw_on_class_notag.morpho
This PR makes adjustments to the Error class to support calling throw and warning on the class without instantiation, e.g. 
`Error.warning("Foo")`
Includes two tests of the fixed functionality. Fixes #252.
> Error class improvements

- modules/povray.morpho
Fixes bug #96 whereby setting quiet=true in POVRaytracer.render did not work correctly on some platforms. The code was redirecting to /dev/null but not setting stderr to also redirect to /dev/null. This now works on linux/ubuntu and macOS.
> Fix povray quiet mode

- src/classes/list.c
- src/classes/range.c
- src/classes/strng.c
- src/morpho.h
- src/support/lex.c
- src/support/lex.h
- src/support/parse.c
- test/class/keyword_method.morpho
- test/class/keyword_property.morpho
This PR updates the parser to allow use of keywords as property and method labels for objects and classes. This will facilitate changing 'prnt' methods to `print` in future (possibly with a deprecation warning). 
```
class A {
init(a) {
self.while = a
}
}
```
> Allow keywords as property and method labels

- src/geometry/functional.c
- src/geometry/functional.h
- test/functionals/areaintegral/cgtensor.morpho
Makes the Cauchy Green strain tensor: 
C = (F G - 1)/2
where: 
* F is the gram matrix in the deformed frame. 
* G is the INVERSE of the gram matrix in the reference frame. 
C vanishes if the deformed and reference frames coincide. 
You must supply a reference mesh to your Integral constructor; you can then call cgtensor() within an integrand:
fn integrand(x, f) {
var cg = cgtensor()
return cg.trace()
}
var a = AreaIntegral(integrand, phi, reference=mref)
> CauchyGreenStrain

- src/geometry/functional.c
- src/geometry/functional.h
- test/functionals/areaintegral/cgtensor.morpho
Adds an option "weightByReference" to AreaIntegral that weights the integral by the reference element rather than the current element. This allows us to express LinearElasticity using AreaIntegral.
> AreaIntegral now supports option weightByReference
