- morpho5/utils/parse.h
- test/arithmetic/power.morpho
- test/test.py
Fixes #5 
I have swapped the order of unary and pow in the precedence list
I have added a few test cases to test/arithmetic/power.morpho (and fixed the test mentioned in #5  that was locking down incorrect behavior)
I have also changed the test harness (test/test.py) to write failed tests to FailedTests.txt
> Bug fixes pow vs uminus

- morpho5/modules/optimize.morpho
Fixed addconstraint in optimize module to calculate the target with a selection
> Fixed optimize module with constraints

- morpho5/builtin/functions.c
- morpho5/datastructures/matrix.c
- morpho5/geometry/field.c
- morpho5/utils/common.c
- test/field/negate.morpho
- test/string/interpolation_types.morpho
Fixes on string interpolation and fields. Addresses #35 and #51.
> String interpolation and negation of field. 

- morpho5/modules/meshtools.morpho
- morpho5/modules/optimize.morpho
Can now fix individual field elements in a FieldOptimizer. 
New options fix= for equiangulate, which enables the user to prevent certain edges being equiangulated.
> Fix field elements and improved meshtools

- morpho5/geometry/field.c
- morpho5/geometry/functional.c
- morpho5/geometry/functional.h
- morpho5/morpho.h
- morpho5/utils/common.c
- test/field/scalarmul.morpho
- test/functionals/lineintegral/fields_incorrect_args.morpho
- test/functionals/lineintegral/fields_insufficient_args.morpho
- test/functionals/lineintegral/fields_toomany_args.morpho
- test/functionals/lineintegral/lineintegral.morpho
Fields can now be divided by a scalar.
Integral functionals now check arguments closing #36 .
> Field division by a scalar

- morpho5/builtin/veneer.c
- morpho5/builtin/veneer.h
- morpho5/datastructures/matrix.c
- morpho5/datastructures/object.c
- morpho5/datastructures/object.h
- morpho5/datastructures/sparse.c
- morpho5/geometry/field.c
- morpho5/geometry/mesh.c
- morpho5/utils/debug.c
- morpho5/vm/compile.c
- morpho5/vm/opcodes.h
- morpho5/vm/vm.c
- test/array/array_dim_with_initializer.morpho
- test/array/array_incompatible_initializer.morpho
- test/array/array_initialize_array.morpho
- test/array/array_initialize_incompatible_list.morpho
- test/array/array_initialize_list.morpho
- test/array/array_print.morpho
- test/array/array_three_dim.morpho
- test/array/arrayinitializers.morpho
- test/array/constructor.morpho
- test/field/scalar.morpho
New array implementation includes: 
1) A more readable objectarray data structure. 
2) Printing arrays. 
3) Arrays can now be initialized with Lists (incl. nested lists) and other arrays. 
4) The compiler now calls the Array() constructor rather than generating OP_ARRAY instructions. 
5) The OP_ARRAY opcode has been withdrawn. 
6) The OP_RAISE opcode has been withdrawn.
> New array implementation

- morpho5/builtin/veneer.c
- morpho5/vm/compile.c
- test/property/property_error_in_index.morpho
- test/string/split_gc.morpho
> Minor bugfixes

- morpho5/datastructures/value.c
- morpho5/datastructures/value.h
Into a regular function. This avoids a possible bug/C violation, fixing #118
> Change morpho_isfalse

- morpho5/builtin/file.c
- morpho5/builtin/file.h
- test/file/remote.morpho
- test/vtk/square.vtk
- test/vtk/tetrahedron.vtk
Now a C class to avoid hiding a bare pointer in an instance. Fixes major issue on M1.
> Reimplemented FIle class

- morpho5/builtin/builtin.c
- morpho5/builtin/file.c
- morpho5/builtin/file.h
- morpho5/builtin/system.c
- morpho5/builtin/system.h
- morpho5/docs/file.md
- morpho5/docs/index.rst
- morpho5/docs/system.md
- test/file/folder.morpho
- test/file/folder/file1.txt
- test/file/folder/file2.txt
- test/file/folder/file3.txt
- test/system/system.morpho
Modest new System class to provide platform dependent features. 
There's also a new Folder class to query the filing system.
> System class

- README.md
added a table of contents
added a instruction to check if the target has an m1 chip
added m1 chip instructions
added instruction on how to add line to ~/.bashrc
> New install instructions

- morpho5/docs/graphics.md
- morpho5/modules/graphics.morpho
- morphoview/command.c
- morphoview/command.h
- testview/textrotate
Updated graphics module: 
1. Now supports text display. 
2. Performance improvements for Show. 
3. Show now uses visitor pattern consistently.
> New graphics module

- morpho5/geometry/mesh.c
- morpho5/geometry/mesh.h
- test/mesh/removegrade.morpho
> Mesh_removegrade added

- morpho5/docs/builtin.md
- morpho5/docs/delaunay.md
- morpho5/docs/meshtools.md
- morpho5/modules/delaunay.morpho
- morpho5/modules/meshtools.morpho
- test/modules/meshtools/testprune.morpho
- test/modules/meshtools/testrefineselection.morpho
* MeshPruner added that enables coarsening of meshes. 
* Improvements to MeshMerge, which now doesn't elements with duplicate vertices. 
* Improvements to selection refinement, which now adds in additional vertices generated in the process of refinement. 
* Refinement of 3D elements. 
* Improvements to documentation
> Improvements to mesh tools

- examples/plot/plotfield.morpho
- examples/plot/plotmeshlabels.morpho
- examples/plot/plotselection.morpho
- examples/plot/scalebar.morpho
- morpho5/docs/functionals.md
- morpho5/docs/plot.md
- morpho5/modules/plot.morpho
Includes: 
* scale bars, implemented as a ScaleBar object. 
* plotfield now supports scale bars. 
* plotmeshlabels created to enable drawing of element ids. 
* Help updated. 
* New plot examples added to the /examples folder.
> New plot module, documentation and examples

- examples/wrap/wrap.morpho
- morpho5/docs/meshgen.md
- morpho5/geometry/functional.c
- morpho5/modules/meshgen.morpho
- morpho5/modules/optimize.morpho
- test/functionals/equielement/equielement.morpho
- test/functionals/equielement/equielement_gradient.morpho
Equielement now evaluates the gradient correctly — test added.
Fixed optimizer now recovers gracefully from failing to bracket stepsize, etc.
Added RectangularDomain to meshgen to easily enable creation of rectangular domains.
> Fixequielement

- morpho5/build.h
- morpho5/builtin/veneer.c
- morpho5/builtin/veneer.h
- morpho5/datastructures/sparse.c
- morpho5/geometry/mesh.c
- morpho5/morpho.h
- morpho5/vm/vm.c
Fixes to size tracking for several object types.
> Sizetracking

- morpho5/utils/debug.c
Minor fix to debugger which would segfault on a file with just '@'
> Fix location information

- morpho5/modules/meshslice.morpho
- morpho5/modules/plot.morpho
Meshslice now works with Fields with higher grades. Values are copied down.
> Meshslice update

- morpho5/geometry/functional.c
- morpho5/utils/debug.c
- morpho5/vm/vm.c
AreaIntegral normals now 3D.
Off by one error in stack display in debugger.
> Fixes for areaintegral

- morpho5/builtin/builtin.c
- morpho5/builtin/builtin.h
- morpho5/utils/common.c
- morpho5/vm/vm.c
- test/functionals/volumeintegral/testintegrals.morpho
Minor fixes to resource loader
> Fixresloader

- morpho5/builtin/veneer.c
- morpho5/datastructures/object.c
- morpho5/datastructures/object.h
- morpho5/geometry/functional.c
- morpho5/utils/debug.c
- morpho5/utils/debug.h
- morpho5/vm/compile.c
- morpho5/vm/core.h
- morpho5/vm/vm.c
- test/property/on_instance.morpho
Modifications to debug_print 
1) print global variables 
2) print object properties, e.g. print foo.boo
> Debug improvements

- morpho5/geometry/field.c
- morpho5/geometry/field.h
- test/field/linearize.morpho
Modifies the behavior of linearize as described in #222, but now merging onto dev
> Safelinearize

- examples/examples.py
- morpho5/Makefile
- morpho5/Makefile.linux
- morpho5/Makefile.m1
- morpho5/geometry/functional.c
- morpho5/geometry/functional.h
Adds missing API to provide analytical field gradients in functionals.
> functional_mapfieldgradient

- src/classes/json.c
- src/core/compile.c
- src/core/vm.c
- src/datastructures/error.c
- src/datastructures/error.h
- src/debug/debug.c
- src/morpho.h
- src/support/lex.c
- src/support/parse.c
Improves the reporting of error messages, which now includes module information if available.
> Module info

- src/builtin/builtin.c
- src/builtin/builtin.h
- src/datastructures/signature.c
- src/datastructures/signature.h
Adds support for multiple dispatch on builtin (C) functions. Improves function signatures to include a return type, which should be useful for type inference.
> Multiple dispatch for builtin functions

- src/classes/list.c
- src/classes/metafunction.c
- src/core/vm.c
- src/datastructures/signature.c
- src/linalg/sparse.c
- test/matrix/concatenate.morpho
- test/sparse/block_constructor_dimensions.morpho
- test/sparse/column.morpho
- test/sparse/sparse_dense_mul.morpho
- test/sparse/sparse_dense_mul_dimensions.morpho
- test/types/multiple_dispatch/apply_invocation_multiple_dispatch.morpho
- test/types/multiple_dispatch/invocation_multiple_dispatch.morpho
Fixes a few bugs: 
- error in Sparse matrix multiplication
- minor compiler memory leaks
- apply() now works correctly with metafunctions
- calling an invocation that involves a metafunction now dispatches correctly.
> v0.6.1 updated version

- releasenotes/version-0.5.1.md
- releasenotes/version-0.5.2.md
- releasenotes/version-0.5.3.md
- src/build.h
- src/core/compile.c
- src/datastructures/syntaxtree.c
- src/datastructures/syntaxtree.h
- src/support/parse.c
- src/support/parse.h
- test/operator/ternary.morpho
- test/operator/ternary_in_function.morpho
- test/operator/ternary_in_loop.morpho
- test/operator/ternary_missing_colon.morpho
- test/operator/ternary_nested.morpho
Implements the ternary operator in morpho: 
```
var c = (a < b ? "yes" : "no") 
```
which is equivalent to:
```
var c 
if (a<b) c="yes"
else c="no"
```
> Ternary operator

- help/plot.md
- modules/plot.morpho
plotfield can now accept a Selection object as an optional argument.
> plotfield now supports Selections

- .github/workflows/codeql.yml
Add manual CodeQL continuous integration.
> Softmattertheory patch 1
